### ISSUE TITLE
Faster slider

### ISSUE THREAD

**Issue by micsondergaard** [wpexplorer/wpex-elegant#9]
Hi - is there a way to speed up the pace of the slides in the front page slider?

**Comment by wpexplorer** [comment]
@micsondergaard  - there isn't any option included so this would require manually editing the file at [js/globaj.js](https://github.com/wpexplorer/wpex-elegant/blob/master/js/global.js#L73) - and you would need to add a "animationSpeed" parameter (default value in flexslider is 600).

I could look at adding an option for this in a future update. But because this theme doesn't have any auto updates you could always just manually update the file. Most people using our themes are actually just renaming them for their clients so they are "custom" and then just tweaking to fit their needs.

- AJ

**Comment by micsondergaard** [comment]
Thanks for your quick reply. Would it be possible for me to pay you to add the animationspeed directly into my WP system?

**Comment by wpexplorer** [comment]
@micsondergaard - it would only take a 1 minute so I can just do it for you free of charge. Send me an email at wpexplorer [at] gmail dot com. And I'll reply back so you can give me your site logins and i can make the tweak for you and record a quick video showing how you can edit it to make it slower/faster in the future.

It's actually 3am here so I'm going to try and get some sleep, I've been working hard on the next big update for [Total](https://total.wpexplorer.com/) and I'm about to crash. But I'm more than happy to help once I get a chance ;)

Or I can just record a quick video showing how you can make the tweak via the WP dashboard and send a link to the video instead so you can try it out yourself and not have to share your site credentials. Let me know if you want to try that out first.

- AJ
